baseURL : 'damilojohn.github.io'
languageCode : 'en-us'
title : 'Home'
theme : 'PaperMod' 
paginate : 5
copyright : Copyright Damilola John &copy; 2023


enableRobotsTXT : true 
enableEmoji: true
markup:
  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(
            - \)
        enable: true


params:
  env: production
  title: Damilola John 
  description : "Personal Blog"
  keywords: [Blog, Portfolio, PaperMod]
  author: Damilola John
  math: true

  homeInfoParams:
    Title: " Damilola John \U0001F44B"
    Content: >
      - **Hi, I'm Damilola, ** Welcome to my blog  
      -   
                     
    imageURL: "1b3.jpg"
  socialIcons:
    - name: twitter 
      url: https://twitter.com/damilojohn
    - name: github
      url: https://github.com/damilojohn
    - name: linkedin 
      url: https://www.linkedin.com/in/oduguwa-damilola/
  profileMode:
        enabled: True
        title: Oduguwa Damilola John # optional default will be site title
        subtitle: > 
          *Hi, I'm Damilola*
            **Welcome to my blog**
                    

        imageUrl: ""
        imageWidth: 300
        imageHeight: 200
        imageTitle: pp
        buttons:
            - name: About Me
              url: "/about"
              weight: 30
            - name: CV 
              url: "./oduguwa-damilola-resume.pdf"
              weight: 30
        
  
  
  ShowBreadCrumbs: true 

  ShowReadingTime: true

  ShowPostNavLinks: true 
  
  ShowCodeCopyButtons: true 

  disableScrollToTop: false 

  ShowToc: true

  defaultTheme : light

  assets : 
    favicon: "/static/favicon.ico"
    favicon16x16: "/static/favicon-16x16.png"
    favicon32x32: "/static/favicon-32x32.png"
    apple_touch_icon: "/static/apple-touch-icon.png"
  
  ShowWordCount: true



menu:
  main:
     - identifier: about
       name: About Me
       url: /about
       weight: 10 
     - identifier: projects
       name: Projects
       url : /projects/
       weight: 20
     - identifier: Articles
       name: Articles
       url: /articles/ 
       weight: 30 
     - identifier: categories
       name: Categories
       url : /Categories/
       weight: 40 
     - identifier: Archives 
       name: Archives
       url: /Archives/
       weight : 40


