baseURL : 'damilojohn.github.io'
languageCode : 'en-us'
title : 'Home'
theme : 'PaperMod' 
paginate : 5
copyright : Copyright Damilola John &copy; 2023


enableRobotsTXT : true 
enableEmoji: true


params:
  env: production
  title: Damilola John 
  description : "Personal Blog"
  keywords: [Blog, Portfolio, PaperMod]
  author: Damilola John

  homeInfoParams:
    Title: " Damilola John \U0001F44B"
    Content: >
      - **Damilola John ** currently studying Computer Engineering at the University of Lagos 
           
      -     A software engineer whose primary focus is in building 
            scalable and transparent Machine learning systems,
            living and studying at the university of lagos.
                     
    imageURL: "1b3.jpg"
  socialIcons:
    - name: twitter 
      url: https://twitter.com/damilojohn
    - name: github
      url: https://github.com/damilojohn
    - name: linkedin 
      url: https://www.linkedin.com/in/oduguwa-damilola-b089131a8/
  profileMode:
        enabled: True
        title: Oduguwa Damilola John # optional default will be site title
        subtitle: >
                **Software Engineer** specializing in **Machine learning**.
                    
                  Passionate about building scalable and transparent Artificial intelligent systems that seamlessly integrate with robust software architectures and  harnessing the power of data to elegantly address
                 complex real world problems. 

                Beyond the world of code, I find myself at the crossroads of technology, Art, Biology, and Astronomy. These disciplines intertwine in my pursuit of innovative solutions, painting a diverse canvas where creativity meets cutting-edge innovation.


        imageUrl: ""
        imageWidth: 300
        imageHeight: 200
        imageTitle: pp
        buttons:
            - name: Articles 
              url: "/posts"
            - name: Projects
              url: "/projects"
            - name: CV 
              url: "./Damilola_John Oduguwa_Resume.pdf"
        
  
  
  ShowBreadCrumbs: true 

  ShowReadingTime: true

  ShowPostNavLinks: true 
  
  ShowCodeCopyButtons: true 

  disableScrollToTop: false 

  ShowToc: true

  defaultTheme : light

  assets : 
    favicon: "/static/favicon.ico"
    favicon16x16: "/static/favicon-16x16.png"
    favicon32x32: "/static/favicon-32x32.png"
    apple_touch_icon: "/static/apple-touch-icon.png"
  
  ShowWordCount: true



menu:
  main:
     - identifier: about
       name: About Me
       url: /about
       weight: 10 
     - identifier: projects
       name: Projects
       url : /projects/
       weight: 20
     - identifier: posts
       name: Posts
       url: /posts/ 
       weight: 30 
     - identifier: categories
       name: Categories
       url : /Categories/
       weight: 40 
     - identifier: Archives 
       name: Archives
       url: /archives/
       weight : 50


